# Generated by Django 4.1.5 on 2023-01-21 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perevodp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('img', models.ImageField(default='perevod/photo.png', upload_to='artist/')),
                ('catgeor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perevodp.catgeoriya')),
            ],
        ),
    ]
