# Generated by Django 4.1.5 on 2023-01-21 19:59

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perevodp', '0002_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('ru_content', ckeditor_uploader.fields.RichTextUploadingField(default=None)),
                ('en_content', ckeditor_uploader.fields.RichTextUploadingField(default=None)),
                ('id_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perevodp.artist')),
            ],
        ),
    ]
