# Generated by Django 4.1.5 on 2023-01-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perevodp', '0003_pesni'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesni',
            name='en_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
