# Generated by Django 4.1.5 on 2023-01-23 07:47

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perevodp', '0004_pesni_en_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesni',
            name='id_artist',
        ),
        migrations.AddField(
            model_name='pesni',
            name='create_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='pesni',
            name='en_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=None, verbose_name='Тексты на английском языке'),
        ),
        migrations.AlterField(
            model_name='pesni',
            name='en_title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Название песни на английском'),
        ),
        migrations.AlterField(
            model_name='pesni',
            name='ru_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=None, verbose_name='Текст песни русский.'),
        ),
        migrations.AlterField(
            model_name='pesni',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Название песни русское.'),
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Catgeoriya',
        ),
    ]
